[2016-11-21 14:36:14,807 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 14:36:14,807 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : ['BOOL'] for client socket on port 1600
[2016-11-21 14:36:14,807 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['BOOL'] for client socket on port 1600
[2016-11-21 14:36:14,807 : set_up_connection - Client @ Client.py (DEBUG)] Connection successful on port 1600.
[2016-11-21 14:36:14,808 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : ['BOOL'] for server socket on port 2600
[2016-11-21 14:36:14,808 : set_sending_datagram - Server @ Server.py (DEBUG)] Sending datagram set to : ['FLOAT'] for server socket on port 2600
[2016-11-21 14:38:14,899 : set_up_connection - Server @ Server.py (INFO)] Timeout : 0 clients connected on port 2600
[2016-11-21 14:38:14,900 : listen_to_clients - Server @ Server.py (WARNING)] No connected client to listen to on port 2600.
[2016-11-21 14:38:49,135 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 14:38:49,136 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : ['BOOL'] for client socket on port 1600
[2016-11-21 14:38:49,136 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['BOOL'] for client socket on port 1600
[2016-11-21 14:38:54,140 : set_up_connection - Client @ Client.py (ERROR)] Connection refused on port 1600. Is the server running with available sockets ?
[2016-11-21 14:38:54,198 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : ['BOOL'] for server socket on port 2600
[2016-11-21 14:38:54,198 : set_sending_datagram - Server @ Server.py (DEBUG)] Sending datagram set to : ['FLOAT'] for server socket on port 2600
[2016-11-21 14:38:54,205 : set_up_connection - Server @ Server.py (INFO)] Maximum amount of clients reached (1) on port 2600
[2016-11-21 14:38:54,206 : set_up_connection - Server @ Server.py (DEBUG)] 1 clients successfuly connected on port 2600
[2016-11-21 14:38:54,206 : listen_to_clients - Server @ Server.py (DEBUG)] Listening to clients on port 2600
[2016-11-21 14:38:54,207 : send_data - Client @ Client.py (WARNING)] Could not send to port 1600 (the socket must be connected in order to send data).
[2016-11-21 14:38:54,207 : receive_data - Client @ Client.py (WARNING)] Could not send to port 1600 (the socket must be connected in order to send data).
[2016-11-21 14:39:11,491 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 14:39:11,492 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : ['BOOL'] for client socket on port 1600
[2016-11-21 14:39:11,492 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['BOOL'] for client socket on port 1600
[2016-11-21 14:39:11,492 : set_up_connection - Client @ Client.py (DEBUG)] Connection successful on port 1600.
[2016-11-21 14:39:11,493 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : ['BOOL'] for server socket on port 2600
[2016-11-21 14:39:11,493 : set_sending_datagram - Server @ Server.py (DEBUG)] Sending datagram set to : ['FLOAT'] for server socket on port 2600
[2016-11-21 14:39:15,435 : set_up_connection - Server @ Server.py (INFO)] Maximum amount of clients reached (1) on port 2600
[2016-11-21 14:39:15,435 : set_up_connection - Server @ Server.py (DEBUG)] 1 clients successfuly connected on port 2600
[2016-11-21 14:39:15,436 : listen_to_clients - Server @ Server.py (DEBUG)] Listening to clients on port 2600
[2016-11-21 14:39:17,743 : close_single_socket - Server @ Server.py (INFO)] Connection on port 2600 closed by client. 0 clients remaining.
[2016-11-21 14:39:17,743 : close_single_socket - Server @ Server.py (INFO)] All clients disconnected on port 2600 closing the connection
[2016-11-21 14:41:30,344 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 14:41:30,344 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : ['BOOL'] for client socket on port 1600
[2016-11-21 14:41:30,344 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['BOOL'] for client socket on port 1600
[2016-11-21 14:41:30,344 : set_up_connection - Client @ Client.py (DEBUG)] Connection successful on port 1600.
[2016-11-21 14:41:30,345 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : ['BOOL'] for server socket on port 2600
[2016-11-21 14:41:30,345 : set_sending_datagram - Server @ Server.py (DEBUG)] Sending datagram set to : ['FLOAT'] for server socket on port 2600
[2016-11-21 14:41:33,187 : set_up_connection - Server @ Server.py (INFO)] Maximum amount of clients reached (1) on port 2600
[2016-11-21 14:41:33,187 : set_up_connection - Server @ Server.py (DEBUG)] 1 clients successfuly connected on port 2600
[2016-11-21 14:41:33,187 : listen_to_clients - Server @ Server.py (DEBUG)] Listening to clients on port 2600
[2016-11-21 14:41:44,804 : close_single_socket - Server @ Server.py (INFO)] Connection on port 2600 closed by client. 0 clients remaining.
[2016-11-21 14:41:44,804 : close_single_socket - Server @ Server.py (INFO)] All clients disconnected on port 2600 closing the connection
[2016-11-21 14:43:45,771 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 14:43:45,771 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : ['BOOL'] for client socket on port 1600
[2016-11-21 14:43:45,772 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['BOOL'] for client socket on port 1600
[2016-11-21 14:43:45,772 : set_up_connection - Client @ Client.py (DEBUG)] Connection successful on port 1600.
[2016-11-21 14:43:45,772 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : ['BOOL'] for server socket on port 2600
[2016-11-21 14:43:45,773 : set_sending_datagram - Server @ Server.py (DEBUG)] Sending datagram set to : ['FLOAT'] for server socket on port 2600
[2016-11-21 14:43:47,431 : set_up_connection - Server @ Server.py (INFO)] Maximum amount of clients reached (1) on port 2600
[2016-11-21 14:43:47,431 : set_up_connection - Server @ Server.py (DEBUG)] 1 clients successfuly connected on port 2600
[2016-11-21 14:43:47,431 : listen_to_clients - Server @ Server.py (DEBUG)] Listening to clients on port 2600
[2016-11-21 14:44:40,091 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 14:44:40,091 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : ['BOOL'] for client socket on port 1600
[2016-11-21 14:44:40,092 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['BOOL'] for client socket on port 1600
[2016-11-21 14:44:40,092 : set_up_connection - Client @ Client.py (DEBUG)] Connection successful on port 1600.
[2016-11-21 14:44:40,092 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : ['BOOL'] for server socket on port 2600
[2016-11-21 14:44:40,093 : set_sending_datagram - Server @ Server.py (DEBUG)] Sending datagram set to : ['FLOAT'] for server socket on port 2600
[2016-11-21 14:44:41,565 : set_up_connection - Server @ Server.py (INFO)] Maximum amount of clients reached (1) on port 2600
[2016-11-21 14:44:41,565 : set_up_connection - Server @ Server.py (DEBUG)] 1 clients successfuly connected on port 2600
[2016-11-21 14:44:41,565 : listen_to_clients - Server @ Server.py (DEBUG)] Listening to clients on port 2600
[2016-11-21 14:44:48,144 : close_single_socket - Server @ Server.py (INFO)] Connection on port 2600 closed by client. 0 clients remaining.
[2016-11-21 14:44:48,144 : close_single_socket - Server @ Server.py (INFO)] All clients disconnected on port 2600 closing the connection
[2016-11-21 14:48:00,286 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 14:48:00,287 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : ['BOOL'] for client socket on port 1600
[2016-11-21 14:48:00,287 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['BOOL'] for client socket on port 1600
[2016-11-21 14:48:00,288 : set_up_connection - Client @ Client.py (DEBUG)] Connection successful on port 1600.
[2016-11-21 14:48:00,288 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : ['BOOL'] for server socket on port 2600
[2016-11-21 14:48:00,288 : set_sending_datagram - Server @ Server.py (DEBUG)] Sending datagram set to : ['FLOAT'] for server socket on port 2600
[2016-11-21 14:48:00,851 : set_up_connection - Server @ Server.py (INFO)] Maximum amount of clients reached (1) on port 2600
[2016-11-21 14:48:00,852 : set_up_connection - Server @ Server.py (DEBUG)] 1 clients successfuly connected on port 2600
[2016-11-21 14:48:00,852 : listen_to_clients - Server @ Server.py (DEBUG)] Listening to clients on port 2600
[2016-11-21 14:48:44,728 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 14:48:44,728 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : ['BOOL'] for client socket on port 1600
[2016-11-21 14:48:44,728 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['BOOL'] for client socket on port 1600
[2016-11-21 14:48:44,729 : set_up_connection - Client @ Client.py (DEBUG)] Connection successful on port 1600.
[2016-11-21 14:48:44,729 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : ['BOOL'] for server socket on port 2600
[2016-11-21 14:48:44,730 : set_sending_datagram - Server @ Server.py (DEBUG)] Sending datagram set to : ['FLOAT'] for server socket on port 2600
[2016-11-21 14:48:46,002 : set_up_connection - Server @ Server.py (INFO)] Maximum amount of clients reached (1) on port 2600
[2016-11-21 14:48:46,003 : set_up_connection - Server @ Server.py (DEBUG)] 1 clients successfuly connected on port 2600
[2016-11-21 14:48:46,003 : listen_to_clients - Server @ Server.py (DEBUG)] Listening to clients on port 2600
[2016-11-21 14:48:57,622 : close_single_socket - Server @ Server.py (INFO)] Connection on port 2600 closed by client. 0 clients remaining.
[2016-11-21 14:48:57,622 : close_single_socket - Server @ Server.py (INFO)] All clients disconnected on port 2600 closing the connection
[2016-11-21 14:50:08,352 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 14:50:08,352 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : ['BOOL'] for client socket on port 1600
[2016-11-21 14:50:08,352 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['BOOL'] for client socket on port 1600
[2016-11-21 14:50:08,353 : set_up_connection - Client @ Client.py (DEBUG)] Connection successful on port 1600.
[2016-11-21 14:50:08,353 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : ['BOOL'] for server socket on port 2600
[2016-11-21 14:50:08,354 : set_sending_datagram - Server @ Server.py (DEBUG)] Sending datagram set to : ['BOOL'] for server socket on port 2600
[2016-11-21 14:50:08,998 : set_up_connection - Server @ Server.py (INFO)] Maximum amount of clients reached (1) on port 2600
[2016-11-21 14:50:08,998 : set_up_connection - Server @ Server.py (DEBUG)] 1 clients successfuly connected on port 2600
[2016-11-21 14:50:08,999 : listen_to_clients - Server @ Server.py (DEBUG)] Listening to clients on port 2600
[2016-11-21 15:15:12,802 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 15:15:12,803 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 15:15:12,804 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : ['SMALL_INT_SIGNED'] for client socket on port 1200
[2016-11-21 15:15:12,804 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : ['SMALL_INT_SIGNED'] for client socket on port 1210
[2016-11-21 15:15:12,805 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['BOOL'] for client socket on port 1200
[2016-11-21 15:15:12,805 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['BOOL'] for client socket on port 1210
[2016-11-21 15:15:12,806 : set_up_connection - Client @ Client.py (DEBUG)] Connection successful on port 1200.
[2016-11-21 15:15:12,818 : set_up_connection - Client @ Client.py (DEBUG)] Connection successful on port 1210.
[2016-11-21 15:15:12,819 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : ['SMALL_INT_SIGNED'] for server socket on port 2200
[2016-11-21 15:15:12,819 : set_sending_datagram - Server @ Server.py (DEBUG)] Sending datagram set to : ['SMALL_INT_SIGNED'] for server socket on port 2200
[2016-11-21 15:16:49,027 : set_up_connection - Server @ Server.py (INFO)] Interrupt received, quit waiting for  on port 2200
[2016-11-21 15:16:49,028 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : ['SMALL_INT_SIGNED'] for server socket on port 2210
[2016-11-21 15:16:49,029 : set_sending_datagram - Server @ Server.py (DEBUG)] Sending datagram set to : ['SMALL_INT_SIGNED'] for server socket on port 2210
[2016-11-21 15:16:49,694 : set_up_connection - Server @ Server.py (INFO)] Interrupt received, quit waiting for  on port 2210
[2016-11-21 15:16:49,695 : listen_to_clients - Server @ Server.py (WARNING)] No connected client to listen to on port 2200.
[2016-11-21 15:16:49,696 : listen_to_clients - Server @ Server.py (WARNING)] No connected client to listen to on port 2210.
[2016-11-21 15:16:51,675 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 15:16:51,675 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 15:16:51,676 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : ['SMALL_INT_SIGNED'] for client socket on port 1200
[2016-11-21 15:16:51,676 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : ['SMALL_INT_SIGNED'] for client socket on port 1210
[2016-11-21 15:16:51,677 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['BOOL'] for client socket on port 1200
[2016-11-21 15:16:51,677 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['BOOL'] for client socket on port 1210
[2016-11-21 15:16:51,678 : set_up_connection - Client @ Client.py (DEBUG)] Connection successful on port 1200.
[2016-11-21 15:16:51,689 : set_up_connection - Client @ Client.py (DEBUG)] Connection successful on port 1210.
[2016-11-21 15:16:51,690 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : ['SMALL_INT_SIGNED'] for server socket on port 2200
[2016-11-21 15:16:51,691 : set_sending_datagram - Server @ Server.py (DEBUG)] Sending datagram set to : ['SMALL_INT_SIGNED'] for server socket on port 2200
[2016-11-21 15:16:55,069 : set_up_connection - Server @ Server.py (INFO)] Maximum amount of clients reached (1) on port 2200
[2016-11-21 15:16:55,070 : set_up_connection - Server @ Server.py (DEBUG)] 1 clients successfuly connected on port 2200
[2016-11-21 15:16:55,071 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : ['SMALL_INT_SIGNED'] for server socket on port 2210
[2016-11-21 15:16:55,071 : set_sending_datagram - Server @ Server.py (DEBUG)] Sending datagram set to : ['SMALL_INT_SIGNED'] for server socket on port 2210
[2016-11-21 15:17:24,103 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 15:17:24,104 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : ['SMALL_INT_SIGNED'] for client socket on port 2210
[2016-11-21 15:17:24,104 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['SMALL_INT_SIGNED'] for client socket on port 2210
[2016-11-21 15:17:24,105 : set_up_connection - Client @ Client.py (DEBUG)] Connection successful on port 2210.
[2016-11-21 15:17:24,105 : set_up_connection - Server @ Server.py (INFO)] Maximum amount of clients reached (1) on port 2210
[2016-11-21 15:17:24,106 : set_up_connection - Server @ Server.py (INFO)] Timeout : 1 clients connected on port 2210
[2016-11-21 15:17:24,107 : set_up_connection - Server @ Server.py (DEBUG)] 1 clients successfuly connected on port 2210
[2016-11-21 15:17:24,107 : listen_to_clients - Server @ Server.py (DEBUG)] Listening to clients on port 2200
[2016-11-21 15:17:24,109 : listen_to_clients - Server @ Server.py (DEBUG)] Listening to clients on port 2210
[2016-11-21 15:35:58,150 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 15:36:31,807 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 15:44:28,039 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 15:44:28,040 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : [['BITS', [1, 1, 1, 1]]] for client socket on port 1300
[2016-11-21 15:44:28,040 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['BOOL'] for client socket on port 1300
[2016-11-21 15:44:28,041 : set_up_connection - Client @ Client.py (DEBUG)] Connection successful on port 1300.
[2016-11-21 15:44:28,042 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : [['BITS', [2, 1]]] for server socket on port 2300
[2016-11-21 15:44:28,042 : set_sending_datagram - Server @ Server.py (DEBUG)] Sending datagram set to : ['BOOL'] for server socket on port 2300
[2016-11-21 15:44:51,664 : set_up_connection - Server @ Server.py (INFO)] Maximum amount of clients reached (1) on port 2300
[2016-11-21 15:44:51,664 : set_up_connection - Server @ Server.py (INFO)] Timeout : 1 clients connected on port 2300
[2016-11-21 15:44:51,665 : set_up_connection - Server @ Server.py (DEBUG)] 1 clients successfuly connected on port 2300
[2016-11-21 15:44:51,666 : listen_to_clients - Server @ Server.py (DEBUG)] Listening to clients on port 2300
[2016-11-21 15:45:56,574 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 15:45:56,575 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : [['BITS', [1, 1, 1, 1]]] for client socket on port 1300
[2016-11-21 15:45:56,575 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['BOOL'] for client socket on port 1300
[2016-11-21 15:45:56,576 : set_up_connection - Client @ Client.py (DEBUG)] Connection successful on port 1300.
[2016-11-21 15:45:56,577 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : [['BITS', [2, 1]]] for server socket on port 2300
[2016-11-21 15:45:56,577 : set_sending_datagram - Server @ Server.py (DEBUG)] Sending datagram set to : ['BOOL'] for server socket on port 2300
[2016-11-21 15:45:59,413 : set_up_connection - Server @ Server.py (INFO)] Maximum amount of clients reached (1) on port 2300
[2016-11-21 15:45:59,414 : set_up_connection - Server @ Server.py (DEBUG)] 1 clients successfuly connected on port 2300
[2016-11-21 15:45:59,415 : listen_to_clients - Server @ Server.py (DEBUG)] Listening to clients on port 2300
[2016-11-21 15:48:54,006 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 15:48:54,007 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : [['BITS', [1, 1, 1, 1]]] for client socket on port 1300
[2016-11-21 15:48:54,008 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['BOOL'] for client socket on port 1300
[2016-11-21 15:48:54,009 : set_up_connection - Client @ Client.py (DEBUG)] Connection successful on port 1300.
[2016-11-21 15:48:54,010 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : [['BITS', [2, 1]]] for server socket on port 2300
[2016-11-21 15:48:54,010 : set_sending_datagram - Server @ Server.py (DEBUG)] Sending datagram set to : ['BOOL'] for server socket on port 2300
[2016-11-21 15:48:55,199 : set_up_connection - Server @ Server.py (INFO)] Maximum amount of clients reached (1) on port 2300
[2016-11-21 15:48:55,200 : set_up_connection - Server @ Server.py (DEBUG)] 1 clients successfuly connected on port 2300
[2016-11-21 15:48:55,201 : listen_to_clients - Server @ Server.py (DEBUG)] Listening to clients on port 2300
[2016-11-21 15:49:57,174 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 15:49:57,175 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : [['BITS', [1, 1, 1, 1]]] for client socket on port 1300
[2016-11-21 15:49:57,176 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['BOOL'] for client socket on port 1300
[2016-11-21 15:49:57,177 : set_up_connection - Client @ Client.py (DEBUG)] Connection successful on port 1300.
[2016-11-21 15:49:57,178 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : [['BITS', [2, 1]]] for server socket on port 2300
[2016-11-21 15:49:57,178 : set_sending_datagram - Server @ Server.py (DEBUG)] Sending datagram set to : ['BOOL'] for server socket on port 2300
[2016-11-21 15:50:01,155 : set_up_connection - Server @ Server.py (INFO)] Maximum amount of clients reached (1) on port 2300
[2016-11-21 15:50:01,155 : set_up_connection - Server @ Server.py (DEBUG)] 1 clients successfuly connected on port 2300
[2016-11-21 15:50:01,156 : listen_to_clients - Server @ Server.py (DEBUG)] Listening to clients on port 2300
[2016-11-21 15:57:02,472 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 15:57:02,473 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : [['BITS', [1, 1, 1, 1]]] for client socket on port 1300
[2016-11-21 15:57:02,474 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['BOOL'] for client socket on port 1300
[2016-11-21 15:57:02,474 : set_up_connection - Client @ Client.py (DEBUG)] Connection successful on port 1300.
[2016-11-21 15:57:02,476 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : [['BITS', [2, 1]]] for server socket on port 2300
[2016-11-21 15:57:02,476 : set_sending_datagram - Server @ Server.py (DEBUG)] Sending datagram set to : ['BOOL'] for server socket on port 2300
[2016-11-21 15:57:04,314 : set_up_connection - Server @ Server.py (INFO)] Maximum amount of clients reached (1) on port 2300
[2016-11-21 15:57:04,315 : set_up_connection - Server @ Server.py (DEBUG)] 1 clients successfuly connected on port 2300
[2016-11-21 15:57:04,316 : listen_to_clients - Server @ Server.py (DEBUG)] Listening to clients on port 2300
[2016-11-21 16:01:40,832 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 16:01:40,832 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : [['BITS', [1, 1, 1, 1]]] for client socket on port 1300
[2016-11-21 16:01:40,833 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['BOOL'] for client socket on port 1300
[2016-11-21 16:01:40,834 : set_up_connection - Client @ Client.py (DEBUG)] Connection successful on port 1300.
[2016-11-21 16:01:40,835 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : [['BITS', [2, 1]]] for server socket on port 2300
[2016-11-21 16:01:40,836 : set_sending_datagram - Server @ Server.py (DEBUG)] Sending datagram set to : ['BOOL'] for server socket on port 2300
[2016-11-21 16:01:44,995 : set_up_connection - Server @ Server.py (INFO)] Maximum amount of clients reached (1) on port 2300
[2016-11-21 16:01:44,996 : set_up_connection - Server @ Server.py (DEBUG)] 1 clients successfuly connected on port 2300
[2016-11-21 16:01:44,997 : listen_to_clients - Server @ Server.py (DEBUG)] Listening to clients on port 2300
[2016-11-21 16:04:09,118 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 16:04:09,119 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : [['BITS', [1, 1, 1, 1]]] for client socket on port 1300
[2016-11-21 16:04:09,119 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['BOOL'] for client socket on port 1300
[2016-11-21 16:04:09,120 : set_up_connection - Client @ Client.py (DEBUG)] Connection successful on port 1300.
[2016-11-21 16:04:09,121 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : [['BITS', [2, 1]]] for server socket on port 2300
[2016-11-21 16:04:09,122 : set_sending_datagram - Server @ Server.py (DEBUG)] Sending datagram set to : ['BOOL'] for server socket on port 2300
[2016-11-21 16:04:11,183 : set_up_connection - Server @ Server.py (INFO)] Maximum amount of clients reached (1) on port 2300
[2016-11-21 16:04:11,183 : set_up_connection - Server @ Server.py (DEBUG)] 1 clients successfuly connected on port 2300
[2016-11-21 16:04:11,184 : listen_to_clients - Server @ Server.py (DEBUG)] Listening to clients on port 2300
[2016-11-21 16:05:09,429 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 16:05:09,430 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : [['BITS', [1, 1, 1, 1]]] for client socket on port 1300
[2016-11-21 16:05:09,431 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['BOOL'] for client socket on port 1300
[2016-11-21 16:05:09,432 : set_up_connection - Client @ Client.py (DEBUG)] Connection successful on port 1300.
[2016-11-21 16:05:09,433 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : [['BITS', [2, 1]]] for server socket on port 2300
[2016-11-21 16:05:09,434 : set_sending_datagram - Server @ Server.py (DEBUG)] Sending datagram set to : ['BOOL'] for server socket on port 2300
[2016-11-21 16:05:10,690 : set_up_connection - Server @ Server.py (INFO)] Maximum amount of clients reached (1) on port 2300
[2016-11-21 16:05:10,691 : set_up_connection - Server @ Server.py (DEBUG)] 1 clients successfuly connected on port 2300
[2016-11-21 16:05:10,692 : listen_to_clients - Server @ Server.py (DEBUG)] Listening to clients on port 2300
[2016-11-21 16:06:11,029 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 16:06:11,030 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : [['BITS', [1, 1, 1, 1]]] for client socket on port 1300
[2016-11-21 16:06:11,030 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['BOOL'] for client socket on port 1300
[2016-11-21 16:06:11,031 : set_up_connection - Client @ Client.py (DEBUG)] Connection successful on port 1300.
[2016-11-21 16:06:11,032 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : [['BITS', [2, 1]]] for server socket on port 2300
[2016-11-21 16:06:11,033 : set_sending_datagram - Server @ Server.py (DEBUG)] Sending datagram set to : ['BOOL'] for server socket on port 2300
[2016-11-21 16:06:12,687 : set_up_connection - Server @ Server.py (INFO)] Maximum amount of clients reached (1) on port 2300
[2016-11-21 16:06:12,687 : set_up_connection - Server @ Server.py (DEBUG)] 1 clients successfuly connected on port 2300
[2016-11-21 16:06:12,689 : listen_to_clients - Server @ Server.py (DEBUG)] Listening to clients on port 2300
[2016-11-21 16:07:14,135 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 16:07:14,136 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : [['BITS', [1, 1, 1, 1]]] for client socket on port 1300
[2016-11-21 16:07:14,137 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['BOOL'] for client socket on port 1300
[2016-11-21 16:07:14,137 : set_up_connection - Client @ Client.py (DEBUG)] Connection successful on port 1300.
[2016-11-21 16:07:14,138 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : [['BITS', [2, 1]]] for server socket on port 2300
[2016-11-21 16:07:14,139 : set_sending_datagram - Server @ Server.py (DEBUG)] Sending datagram set to : ['BOOL'] for server socket on port 2300
[2016-11-21 16:07:15,985 : set_up_connection - Server @ Server.py (INFO)] Maximum amount of clients reached (1) on port 2300
[2016-11-21 16:07:15,985 : set_up_connection - Server @ Server.py (DEBUG)] 1 clients successfuly connected on port 2300
[2016-11-21 16:07:15,986 : listen_to_clients - Server @ Server.py (DEBUG)] Listening to clients on port 2300
[2016-11-21 16:08:40,941 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 16:08:40,942 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : [['BITS', [1, 1, 1, 1]]] for client socket on port 1300
[2016-11-21 16:08:40,942 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['BOOL'] for client socket on port 1300
[2016-11-21 16:08:40,943 : set_up_connection - Client @ Client.py (DEBUG)] Connection successful on port 1300.
[2016-11-21 16:08:40,944 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : [['BITS', [2, 1]]] for server socket on port 2300
[2016-11-21 16:08:40,945 : set_sending_datagram - Server @ Server.py (DEBUG)] Sending datagram set to : ['BOOL'] for server socket on port 2300
[2016-11-21 16:08:42,714 : set_up_connection - Server @ Server.py (INFO)] Maximum amount of clients reached (1) on port 2300
[2016-11-21 16:08:42,715 : set_up_connection - Server @ Server.py (DEBUG)] 1 clients successfuly connected on port 2300
[2016-11-21 16:08:42,716 : listen_to_clients - Server @ Server.py (DEBUG)] Listening to clients on port 2300
[2016-11-21 16:10:19,133 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 16:10:19,134 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : [['BITS', [1, 1, 1, 1]]] for client socket on port 1300
[2016-11-21 16:10:19,134 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['BOOL'] for client socket on port 1300
[2016-11-21 16:10:19,136 : set_up_connection - Client @ Client.py (DEBUG)] Connection successful on port 1300.
[2016-11-21 16:10:19,138 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : [['BITS', [2, 1]]] for server socket on port 2300
[2016-11-21 16:10:19,139 : set_sending_datagram - Server @ Server.py (DEBUG)] Sending datagram set to : ['BOOL'] for server socket on port 2300
[2016-11-21 16:10:20,019 : set_up_connection - Server @ Server.py (INFO)] Maximum amount of clients reached (1) on port 2300
[2016-11-21 16:10:20,020 : set_up_connection - Server @ Server.py (DEBUG)] 1 clients successfuly connected on port 2300
[2016-11-21 16:10:20,021 : listen_to_clients - Server @ Server.py (DEBUG)] Listening to clients on port 2300
[2016-11-21 16:13:22,289 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 16:13:22,290 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : [['BITS', [1, 1, 1, 1]]] for client socket on port 1300
[2016-11-21 16:13:22,290 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['BOOL'] for client socket on port 1300
[2016-11-21 16:13:22,291 : set_up_connection - Client @ Client.py (DEBUG)] Connection successful on port 1300.
[2016-11-21 16:13:22,292 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : [['BITS', [2, 1]]] for server socket on port 2300
[2016-11-21 16:13:22,293 : set_sending_datagram - Server @ Server.py (DEBUG)] Sending datagram set to : ['BOOL'] for server socket on port 2300
[2016-11-21 16:13:24,753 : set_up_connection - Server @ Server.py (INFO)] Maximum amount of clients reached (1) on port 2300
[2016-11-21 16:13:24,753 : set_up_connection - Server @ Server.py (DEBUG)] 1 clients successfuly connected on port 2300
[2016-11-21 16:13:24,754 : listen_to_clients - Server @ Server.py (DEBUG)] Listening to clients on port 2300
[2016-11-21 16:22:47,572 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 16:22:47,573 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : [['BITS', [1, 1, 1, 1]]] for client socket on port 1300
[2016-11-21 16:22:47,573 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['BOOL'] for client socket on port 1300
[2016-11-21 16:22:47,574 : set_up_connection - Client @ Client.py (DEBUG)] Connection successful on port 1300.
[2016-11-21 16:22:47,575 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : [['BITS', [2, 1]]] for server socket on port 2300
[2016-11-21 16:22:47,576 : set_sending_datagram - Server @ Server.py (DEBUG)] Sending datagram set to : ['BOOL'] for server socket on port 2300
[2016-11-21 16:22:49,236 : set_up_connection - Server @ Server.py (INFO)] Maximum amount of clients reached (1) on port 2300
[2016-11-21 16:22:49,237 : set_up_connection - Server @ Server.py (DEBUG)] 1 clients successfuly connected on port 2300
[2016-11-21 16:22:49,238 : listen_to_clients - Server @ Server.py (DEBUG)] Listening to clients on port 2300
[2016-11-21 18:56:26,430 : set_sending_datagram - Server @ Server.py (DEBUG)] Sending datagram set to : ['BOOL'] for server socket on port 1200
[2016-11-21 18:56:26,431 : set_sending_datagram - Server @ Server.py (DEBUG)] Sending datagram set to : ['BOOL'] for server socket on port 1210
[2016-11-21 18:56:26,431 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : ['SMALL_INT_SIGNED'] for server socket on port 1200
[2016-11-21 18:56:26,431 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : ['SMALL_INT_SIGNED'] for server socket on port 1210
[2016-11-21 18:56:33,407 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 18:56:33,408 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 18:56:33,408 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : ['SMALL_INT_SIGNED'] for client socket on port 1200
[2016-11-21 18:56:33,408 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : ['SMALL_INT_SIGNED'] for client socket on port 1210
[2016-11-21 18:56:33,409 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['BOOL'] for client socket on port 1200
[2016-11-21 18:56:33,409 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['BOOL'] for client socket on port 1210
[2016-11-21 18:56:33,410 : set_up_connection - Server @ Server.py (INFO)] Maximum amount of clients reached (1) on port 1200
[2016-11-21 18:56:33,410 : set_up_connection - Client @ Client.py (DEBUG)] Connection successful on port 1200.
[2016-11-21 18:56:33,411 : set_up_connection - Server @ Server.py (DEBUG)] 1 clients successfuly connected on port 1200
[2016-11-21 18:56:33,422 : set_up_connection - Client @ Client.py (DEBUG)] Connection successful on port 1210.
[2016-11-21 18:56:33,423 : set_up_connection - Server @ Server.py (INFO)] Maximum amount of clients reached (1) on port 1210
[2016-11-21 18:56:33,423 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : ['SMALL_INT_SIGNED'] for server socket on port 2200
[2016-11-21 18:56:33,423 : set_up_connection - Server @ Server.py (DEBUG)] 1 clients successfuly connected on port 1210
[2016-11-21 18:56:33,424 : set_sending_datagram - Server @ Server.py (DEBUG)] Sending datagram set to : ['SMALL_INT_SIGNED'] for server socket on port 2200
[2016-11-21 18:56:33,424 : listen_to_clients - Server @ Server.py (DEBUG)] Listening to clients on port 1200
[2016-11-21 18:56:33,426 : listen_to_clients - Server @ Server.py (DEBUG)] Listening to clients on port 1210
[2016-11-21 18:56:39,820 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 18:56:39,821 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : ['SMALL_INT_SIGNED'] for client socket on port 2200
[2016-11-21 18:56:39,821 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['SMALL_INT_SIGNED'] for client socket on port 2200
[2016-11-21 18:56:39,822 : set_up_connection - Server @ Server.py (INFO)] Maximum amount of clients reached (1) on port 2200
[2016-11-21 18:56:39,822 : set_up_connection - Client @ Client.py (DEBUG)] Connection successful on port 2200.
[2016-11-21 18:56:39,823 : set_up_connection - Server @ Server.py (INFO)] Timeout : 1 clients connected on port 2200
[2016-11-21 18:56:39,823 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : ['BOOL'] for server socket on port 3100
[2016-11-21 18:56:39,824 : set_up_connection - Server @ Server.py (DEBUG)] 1 clients successfuly connected on port 2200
[2016-11-21 18:56:39,825 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : ['SMALL_INT_SIGNED'] for server socket on port 2210
[2016-11-21 18:56:39,825 : set_sending_datagram - Server @ Server.py (DEBUG)] Sending datagram set to : ['SMALL_INT_SIGNED'] for server socket on port 2210
[2016-11-21 18:56:45,250 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 18:56:45,251 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : ['BOOL'] for client socket on port 2600
[2016-11-21 18:56:45,252 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['BOOL'] for client socket on port 2600
[2016-11-21 18:56:50,258 : set_up_connection - Client @ Client.py (ERROR)] Connection refused on port 2600. Is the server running with available sockets ?
[2016-11-21 18:56:50,260 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 18:56:50,260 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : ['BOOL'] for client socket on port 3100
[2016-11-21 18:56:50,261 : set_up_connection - Client @ Client.py (DEBUG)] Connection successful on port 3100.
[2016-11-21 18:56:50,261 : set_up_connection - Server @ Server.py (INFO)] Maximum amount of clients reached (1) on port 3100
[2016-11-21 18:56:50,262 : set_up_connection - Server @ Server.py (INFO)] Timeout : 1 clients connected on port 3100
[2016-11-21 18:56:50,262 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 18:56:50,263 : set_up_connection - Server @ Server.py (DEBUG)] 1 clients successfuly connected on port 3100
[2016-11-21 18:56:50,263 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 18:56:50,264 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : ['SMALL_INT_SIGNED'] for server socket on port 3110
[2016-11-21 18:56:50,265 : set_sending_datagram - Server @ Server.py (DEBUG)] Sending datagram set to : ['BOOL'] for server socket on port 3110
[2016-11-21 18:56:50,351 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 18:56:50,352 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : ['SMALL_INT_SIGNED'] for client socket on port 2210
[2016-11-21 18:56:50,353 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['SMALL_INT_SIGNED'] for client socket on port 2210
[2016-11-21 18:56:50,354 : set_up_connection - Server @ Server.py (INFO)] Maximum amount of clients reached (1) on port 2210
[2016-11-21 18:56:50,354 : set_up_connection - Client @ Client.py (DEBUG)] Connection successful on port 2210.
[2016-11-21 18:56:50,355 : set_up_connection - Server @ Server.py (INFO)] Timeout : 1 clients connected on port 2210
[2016-11-21 18:56:50,355 : set_up_connection - Server @ Server.py (DEBUG)] 1 clients successfuly connected on port 2210
[2016-11-21 18:56:50,356 : listen_to_clients - Server @ Server.py (DEBUG)] Listening to clients on port 2200
[2016-11-21 18:56:50,357 : listen_to_clients - Server @ Server.py (DEBUG)] Listening to clients on port 2210
[2016-11-21 18:57:07,134 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 18:57:07,135 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : ['SMALL_INT_SIGNED'] for client socket on port 3110
[2016-11-21 18:57:07,135 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['BOOL'] for client socket on port 3110
[2016-11-21 18:57:07,136 : set_up_connection - Client @ Client.py (DEBUG)] Connection successful on port 3110.
[2016-11-21 18:57:07,136 : set_up_connection - Server @ Server.py (INFO)] Maximum amount of clients reached (1) on port 3110
[2016-11-21 18:57:07,137 : set_up_connection - Server @ Server.py (DEBUG)] 1 clients successfuly connected on port 3110
[2016-11-21 18:57:07,138 : listen_to_clients - Server @ Server.py (DEBUG)] Listening to clients on port 3110
[2016-11-21 18:57:07,139 : listen_to_clients - Server @ Server.py (DEBUG)] Listening to clients on port 3100
[2016-11-21 18:57:14,166 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 5
[2016-11-21 18:57:14,167 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 5
[2016-11-21 18:57:14,419 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 10
[2016-11-21 18:57:14,419 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 10
[2016-11-21 18:57:14,668 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 15
[2016-11-21 18:57:14,670 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 15
[2016-11-21 18:57:14,920 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 20
[2016-11-21 18:57:14,922 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 20
[2016-11-21 18:57:15,171 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 25
[2016-11-21 18:57:15,175 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 25
[2016-11-21 18:57:15,424 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 30
[2016-11-21 18:57:15,425 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 30
[2016-11-21 18:57:15,677 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 40
[2016-11-21 18:57:15,678 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 40
[2016-11-21 18:57:15,927 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:15,929 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:16,178 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:16,180 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:16,431 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:16,433 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:16,685 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:16,686 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:16,935 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:16,937 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:17,188 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:17,189 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:17,440 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:17,440 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:17,692 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:17,693 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:17,942 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:17,944 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:18,195 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:18,197 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:18,446 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:18,449 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:18,697 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:18,700 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:18,951 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:18,952 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:19,204 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:19,206 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:19,453 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:19,455 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:19,707 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:19,707 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:19,957 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:19,959 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:20,210 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:20,211 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:20,462 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:20,463 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:20,715 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:20,716 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:20,965 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:20,966 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:21,216 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:21,218 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:21,469 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:21,470 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:21,721 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:21,721 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:21,972 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:21,974 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:22,225 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:22,226 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:22,476 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:22,478 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:22,728 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:22,729 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:22,980 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:22,981 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:23,233 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:23,234 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:23,484 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:23,485 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:23,734 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:23,736 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:23,988 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:23,989 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:24,240 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:24,243 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:24,491 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:24,492 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:24,741 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:24,743 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:24,996 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:24,997 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:25,245 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:25,247 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:25,499 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:25,500 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:25,749 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:25,752 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:26,001 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:26,004 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:26,253 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:26,255 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:26,507 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:26,513 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:26,761 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:26,769 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:27,020 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:27,022 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:27,278 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:27,281 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:27,531 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:27,538 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:27,795 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:27,799 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:28,052 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:28,052 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:28,299 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:28,305 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:28,555 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:28,555 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:28,807 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:28,808 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:29,060 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:29,060 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:29,313 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:29,314 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:29,562 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:29,563 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:29,823 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the right motor to go forward with a PWM of 50
[2016-11-21 18:57:29,824 : set_pwm_cb - mot @ mot.py (DEBUG)] Setting the left motor to go forward with a PWM of 50
[2016-11-21 18:57:30,970 : close_single_socket - Server @ Server.py (INFO)] Connection on port 1210 closed by client. 0 clients remaining.
[2016-11-21 18:57:30,972 : close_single_socket - Server @ Server.py (INFO)] All clients disconnected on port 1210 closing the connection
[2016-11-21 18:57:30,973 : close_single_socket - Server @ Server.py (INFO)] Connection on port 1200 closed by client. 0 clients remaining.
[2016-11-21 18:57:30,974 : close_single_socket - Server @ Server.py (INFO)] All clients disconnected on port 1200 closing the connection
[2016-11-21 18:59:39,239 : set_sending_datagram - Server @ Server.py (DEBUG)] Sending datagram set to : ['BOOL'] for server socket on port 1200
[2016-11-21 18:59:39,240 : set_sending_datagram - Server @ Server.py (DEBUG)] Sending datagram set to : ['BOOL'] for server socket on port 1210
[2016-11-21 18:59:39,240 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : ['SMALL_INT_SIGNED'] for server socket on port 1200
[2016-11-21 18:59:39,241 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : ['SMALL_INT_SIGNED'] for server socket on port 1210
[2016-11-21 18:59:41,562 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 18:59:41,563 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 18:59:41,564 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : ['SMALL_INT_SIGNED'] for client socket on port 1200
[2016-11-21 18:59:41,564 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : ['SMALL_INT_SIGNED'] for client socket on port 1210
[2016-11-21 18:59:41,565 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['BOOL'] for client socket on port 1200
[2016-11-21 18:59:41,566 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['BOOL'] for client socket on port 1210
[2016-11-21 18:59:41,567 : set_up_connection - Server @ Server.py (INFO)] Maximum amount of clients reached (1) on port 1200
[2016-11-21 18:59:41,568 : set_up_connection - Server @ Server.py (DEBUG)] 1 clients successfuly connected on port 1200
[2016-11-21 18:59:41,569 : set_up_connection - Client @ Client.py (DEBUG)] Connection successful on port 1200.
[2016-11-21 18:59:41,573 : set_up_connection - Server @ Server.py (INFO)] Maximum amount of clients reached (1) on port 1210
[2016-11-21 18:59:41,574 : set_up_connection - Server @ Server.py (DEBUG)] 1 clients successfuly connected on port 1210
[2016-11-21 18:59:41,575 : listen_to_clients - Server @ Server.py (DEBUG)] Listening to clients on port 1200
[2016-11-21 18:59:41,577 : set_up_connection - Client @ Client.py (DEBUG)] Connection successful on port 1210.
[2016-11-21 18:59:41,578 : listen_to_clients - Server @ Server.py (DEBUG)] Listening to clients on port 1210
[2016-11-21 18:59:41,578 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : ['SMALL_INT_SIGNED'] for server socket on port 2200
[2016-11-21 18:59:41,579 : set_sending_datagram - Server @ Server.py (DEBUG)] Sending datagram set to : ['SMALL_INT_SIGNED'] for server socket on port 2200
[2016-11-21 18:59:43,554 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 18:59:43,555 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : ['BOOL'] for client socket on port 2600
[2016-11-21 18:59:43,556 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['BOOL'] for client socket on port 2600
[2016-11-21 18:59:48,566 : set_up_connection - Client @ Client.py (ERROR)] Connection refused on port 2600. Is the server running with available sockets ?
[2016-11-21 18:59:48,569 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 18:59:48,571 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : ['BOOL'] for client socket on port 3100
[2016-11-21 18:59:48,628 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 18:59:48,628 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : ['SMALL_INT_SIGNED'] for client socket on port 2210
[2016-11-21 18:59:48,629 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['SMALL_INT_SIGNED'] for client socket on port 2210
[2016-11-21 18:59:50,433 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 18:59:50,434 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : ['SMALL_INT_SIGNED'] for client socket on port 3110
[2016-11-21 18:59:50,434 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['BOOL'] for client socket on port 3110
[2016-11-21 18:59:53,581 : set_up_connection - Client @ Client.py (ERROR)] Connection refused on port 3100. Is the server running with available sockets ?
[2016-11-21 18:59:53,582 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 18:59:53,593 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:00:11,805 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 19:00:11,806 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : ['SMALL_INT_SIGNED'] for client socket on port 2200
[2016-11-21 19:00:11,806 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['SMALL_INT_SIGNED'] for client socket on port 2200
[2016-11-21 19:00:11,807 : set_up_connection - Client @ Client.py (DEBUG)] Connection successful on port 2200.
[2016-11-21 19:00:11,807 : set_up_connection - Server @ Server.py (INFO)] Maximum amount of clients reached (1) on port 2200
[2016-11-21 19:00:11,808 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : ['BOOL'] for server socket on port 3100
[2016-11-21 19:00:11,808 : set_up_connection - Server @ Server.py (INFO)] Timeout : 1 clients connected on port 2200
[2016-11-21 19:00:11,808 : set_up_connection - Server @ Server.py (DEBUG)] 1 clients successfuly connected on port 2200
[2016-11-21 19:00:11,810 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : ['SMALL_INT_SIGNED'] for server socket on port 2210
[2016-11-21 19:00:11,810 : set_sending_datagram - Server @ Server.py (DEBUG)] Sending datagram set to : ['SMALL_INT_SIGNED'] for server socket on port 2210
[2016-11-21 19:00:11,814 : set_up_connection - Server @ Server.py (INFO)] Maximum amount of clients reached (1) on port 2210
[2016-11-21 19:00:11,814 : set_up_connection - Client @ Client.py (DEBUG)] Connection successful on port 2210.
[2016-11-21 19:00:11,816 : set_up_connection - Server @ Server.py (DEBUG)] 1 clients successfuly connected on port 2210
[2016-11-21 19:00:11,816 : listen_to_clients - Server @ Server.py (DEBUG)] Listening to clients on port 2200
[2016-11-21 19:00:11,818 : listen_to_clients - Server @ Server.py (DEBUG)] Listening to clients on port 2210
[2016-11-21 19:00:22,088 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 19:00:22,088 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : ['SMALL_INT_SIGNED'] for client socket on port 3110
[2016-11-21 19:00:22,089 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['BOOL'] for client socket on port 3110
[2016-11-21 19:00:25,323 : set_up_connection - Server @ Server.py (INFO)] Interrupt received, quit waiting for  on port 3100
[2016-11-21 19:00:25,325 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : ['SMALL_INT_SIGNED'] for server socket on port 3110
[2016-11-21 19:00:25,326 : set_sending_datagram - Server @ Server.py (DEBUG)] Sending datagram set to : ['BOOL'] for server socket on port 3110
[2016-11-21 19:02:23,613 : set_sending_datagram - Server @ Server.py (DEBUG)] Sending datagram set to : ['BOOL'] for server socket on port 1200
[2016-11-21 19:02:23,614 : set_sending_datagram - Server @ Server.py (DEBUG)] Sending datagram set to : ['BOOL'] for server socket on port 1210
[2016-11-21 19:02:23,614 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : ['SMALL_INT_SIGNED'] for server socket on port 1200
[2016-11-21 19:02:23,615 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : ['SMALL_INT_SIGNED'] for server socket on port 1210
[2016-11-21 19:02:25,359 : set_up_connection - Server @ Server.py (INFO)] Timeout : 0 clients connected on port 3110
[2016-11-21 19:02:25,361 : listen_to_clients - Server @ Server.py (WARNING)] No connected client to listen to on port 3110.
[2016-11-21 19:02:25,361 : listen_to_clients - Server @ Server.py (WARNING)] No connected client to listen to on port 3100.
[2016-11-21 19:02:26,109 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 19:02:26,110 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 19:02:26,110 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : ['SMALL_INT_SIGNED'] for client socket on port 1200
[2016-11-21 19:02:26,111 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : ['SMALL_INT_SIGNED'] for client socket on port 1210
[2016-11-21 19:02:26,111 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['BOOL'] for client socket on port 1200
[2016-11-21 19:02:26,111 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['BOOL'] for client socket on port 1210
[2016-11-21 19:02:26,112 : set_up_connection - Client @ Client.py (DEBUG)] Connection successful on port 1200.
[2016-11-21 19:02:26,112 : set_up_connection - Server @ Server.py (INFO)] Maximum amount of clients reached (1) on port 1200
[2016-11-21 19:02:26,113 : set_up_connection - Server @ Server.py (DEBUG)] 1 clients successfuly connected on port 1200
[2016-11-21 19:02:26,123 : set_up_connection - Client @ Client.py (DEBUG)] Connection successful on port 1210.
[2016-11-21 19:02:26,124 : set_up_connection - Server @ Server.py (INFO)] Maximum amount of clients reached (1) on port 1210
[2016-11-21 19:02:26,124 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : ['SMALL_INT_SIGNED'] for server socket on port 2200
[2016-11-21 19:02:26,125 : set_up_connection - Server @ Server.py (DEBUG)] 1 clients successfuly connected on port 1210
[2016-11-21 19:02:26,125 : set_sending_datagram - Server @ Server.py (DEBUG)] Sending datagram set to : ['SMALL_INT_SIGNED'] for server socket on port 2200
[2016-11-21 19:02:26,126 : listen_to_clients - Server @ Server.py (DEBUG)] Listening to clients on port 1200
[2016-11-21 19:02:26,128 : listen_to_clients - Server @ Server.py (DEBUG)] Listening to clients on port 1210
[2016-11-21 19:02:28,370 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 19:02:28,371 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : ['BOOL'] for client socket on port 2600
[2016-11-21 19:02:28,371 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['BOOL'] for client socket on port 2600
[2016-11-21 19:02:30,597 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 19:02:30,597 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : ['SMALL_INT_SIGNED'] for client socket on port 2210
[2016-11-21 19:02:30,598 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['SMALL_INT_SIGNED'] for client socket on port 2210
[2016-11-21 19:02:32,678 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 19:02:32,679 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : ['SMALL_INT_SIGNED'] for client socket on port 3110
[2016-11-21 19:02:32,679 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['BOOL'] for client socket on port 3110
[2016-11-21 19:02:33,373 : set_up_connection - Client @ Client.py (ERROR)] Connection refused on port 2600. Is the server running with available sockets ?
[2016-11-21 19:02:33,375 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 19:02:33,375 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : ['BOOL'] for client socket on port 3100
[2016-11-21 19:02:38,384 : set_up_connection - Client @ Client.py (ERROR)] Connection refused on port 3100. Is the server running with available sockets ?
[2016-11-21 19:02:38,385 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:38,397 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:38,398 : send_data - Client @ Client.py (WARNING)] Could not send to port 3100 (the socket must be connected in order to send data).
[2016-11-21 19:02:38,499 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:38,510 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:38,511 : send_data - Client @ Client.py (WARNING)] Could not send to port 3100 (the socket must be connected in order to send data).
[2016-11-21 19:02:38,612 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:38,624 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:38,625 : send_data - Client @ Client.py (WARNING)] Could not send to port 3100 (the socket must be connected in order to send data).
[2016-11-21 19:02:38,726 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:38,737 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:38,738 : send_data - Client @ Client.py (WARNING)] Could not send to port 3100 (the socket must be connected in order to send data).
[2016-11-21 19:02:38,839 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:38,850 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:38,852 : send_data - Client @ Client.py (WARNING)] Could not send to port 3100 (the socket must be connected in order to send data).
[2016-11-21 19:02:38,953 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:38,964 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:38,966 : send_data - Client @ Client.py (WARNING)] Could not send to port 3100 (the socket must be connected in order to send data).
[2016-11-21 19:02:39,066 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:39,078 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:39,079 : send_data - Client @ Client.py (WARNING)] Could not send to port 3100 (the socket must be connected in order to send data).
[2016-11-21 19:02:39,180 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:39,192 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:39,193 : send_data - Client @ Client.py (WARNING)] Could not send to port 3100 (the socket must be connected in order to send data).
[2016-11-21 19:02:39,294 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:39,305 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:39,307 : send_data - Client @ Client.py (WARNING)] Could not send to port 3100 (the socket must be connected in order to send data).
[2016-11-21 19:02:39,408 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:39,419 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:39,421 : send_data - Client @ Client.py (WARNING)] Could not send to port 3100 (the socket must be connected in order to send data).
[2016-11-21 19:02:39,524 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:39,535 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:39,536 : send_data - Client @ Client.py (WARNING)] Could not send to port 3100 (the socket must be connected in order to send data).
[2016-11-21 19:02:39,637 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:39,649 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:39,651 : send_data - Client @ Client.py (WARNING)] Could not send to port 3100 (the socket must be connected in order to send data).
[2016-11-21 19:02:39,752 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:39,764 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:39,765 : send_data - Client @ Client.py (WARNING)] Could not send to port 3100 (the socket must be connected in order to send data).
[2016-11-21 19:02:39,865 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:39,877 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:39,878 : send_data - Client @ Client.py (WARNING)] Could not send to port 3100 (the socket must be connected in order to send data).
[2016-11-21 19:02:39,978 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:39,990 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:39,991 : send_data - Client @ Client.py (WARNING)] Could not send to port 3100 (the socket must be connected in order to send data).
[2016-11-21 19:02:40,092 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:40,103 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:40,104 : send_data - Client @ Client.py (WARNING)] Could not send to port 3100 (the socket must be connected in order to send data).
[2016-11-21 19:02:40,205 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:40,217 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:40,218 : send_data - Client @ Client.py (WARNING)] Could not send to port 3100 (the socket must be connected in order to send data).
[2016-11-21 19:02:40,319 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:40,331 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:40,332 : send_data - Client @ Client.py (WARNING)] Could not send to port 3100 (the socket must be connected in order to send data).
[2016-11-21 19:02:40,432 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:40,444 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:40,445 : send_data - Client @ Client.py (WARNING)] Could not send to port 3100 (the socket must be connected in order to send data).
[2016-11-21 19:02:40,546 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:40,558 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:40,559 : send_data - Client @ Client.py (WARNING)] Could not send to port 3100 (the socket must be connected in order to send data).
[2016-11-21 19:02:40,660 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:40,671 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:40,672 : send_data - Client @ Client.py (WARNING)] Could not send to port 3100 (the socket must be connected in order to send data).
[2016-11-21 19:02:40,773 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:40,784 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:40,785 : send_data - Client @ Client.py (WARNING)] Could not send to port 3100 (the socket must be connected in order to send data).
[2016-11-21 19:02:40,886 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:40,898 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:40,899 : send_data - Client @ Client.py (WARNING)] Could not send to port 3100 (the socket must be connected in order to send data).
[2016-11-21 19:02:40,999 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:41,011 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:41,013 : send_data - Client @ Client.py (WARNING)] Could not send to port 3100 (the socket must be connected in order to send data).
[2016-11-21 19:02:41,114 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:41,126 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:41,127 : send_data - Client @ Client.py (WARNING)] Could not send to port 3100 (the socket must be connected in order to send data).
[2016-11-21 19:02:41,190 : set_up_connection - Server @ Server.py (INFO)] Interrupt received, quit waiting for  on port 2200
[2016-11-21 19:02:41,192 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : ['SMALL_INT_SIGNED'] for server socket on port 2210
[2016-11-21 19:02:41,192 : set_sending_datagram - Server @ Server.py (DEBUG)] Sending datagram set to : ['SMALL_INT_SIGNED'] for server socket on port 2210
[2016-11-21 19:02:41,228 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:41,239 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:41,241 : send_data - Client @ Client.py (WARNING)] Could not send to port 3100 (the socket must be connected in order to send data).
[2016-11-21 19:02:41,342 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:41,353 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:41,355 : send_data - Client @ Client.py (WARNING)] Could not send to port 3100 (the socket must be connected in order to send data).
[2016-11-21 19:02:41,456 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:41,467 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:41,468 : send_data - Client @ Client.py (WARNING)] Could not send to port 3100 (the socket must be connected in order to send data).
[2016-11-21 19:02:41,569 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:41,580 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:41,582 : send_data - Client @ Client.py (WARNING)] Could not send to port 3100 (the socket must be connected in order to send data).
[2016-11-21 19:02:41,683 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:41,694 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:41,696 : send_data - Client @ Client.py (WARNING)] Could not send to port 3100 (the socket must be connected in order to send data).
[2016-11-21 19:02:41,797 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:41,810 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:41,811 : send_data - Client @ Client.py (WARNING)] Could not send to port 3100 (the socket must be connected in order to send data).
[2016-11-21 19:02:41,912 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:41,923 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:41,925 : send_data - Client @ Client.py (WARNING)] Could not send to port 3100 (the socket must be connected in order to send data).
[2016-11-21 19:02:42,026 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:42,037 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:42,038 : send_data - Client @ Client.py (WARNING)] Could not send to port 3100 (the socket must be connected in order to send data).
[2016-11-21 19:02:42,139 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:42,151 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:42,152 : send_data - Client @ Client.py (WARNING)] Could not send to port 3100 (the socket must be connected in order to send data).
[2016-11-21 19:02:42,216 : set_up_connection - Server @ Server.py (INFO)] Interrupt received, quit waiting for  on port 2210
[2016-11-21 19:02:42,217 : listen_to_clients - Server @ Server.py (WARNING)] No connected client to listen to on port 2200.
[2016-11-21 19:02:42,217 : listen_to_clients - Server @ Server.py (WARNING)] No connected client to listen to on port 2210.
[2016-11-21 19:02:42,252 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:42,264 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:42,265 : send_data - Client @ Client.py (WARNING)] Could not send to port 3100 (the socket must be connected in order to send data).
[2016-11-21 19:02:42,366 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:42,377 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:42,379 : send_data - Client @ Client.py (WARNING)] Could not send to port 3100 (the socket must be connected in order to send data).
[2016-11-21 19:02:42,480 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:42,491 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:42,492 : send_data - Client @ Client.py (WARNING)] Could not send to port 3100 (the socket must be connected in order to send data).
[2016-11-21 19:02:42,593 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:42,605 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:42,606 : send_data - Client @ Client.py (WARNING)] Could not send to port 3100 (the socket must be connected in order to send data).
[2016-11-21 19:02:42,707 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:42,719 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:42,720 : send_data - Client @ Client.py (WARNING)] Could not send to port 3100 (the socket must be connected in order to send data).
[2016-11-21 19:02:42,820 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:42,834 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:42,835 : send_data - Client @ Client.py (WARNING)] Could not send to port 3100 (the socket must be connected in order to send data).
[2016-11-21 19:02:42,937 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:42,952 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:42,953 : send_data - Client @ Client.py (WARNING)] Could not send to port 3100 (the socket must be connected in order to send data).
[2016-11-21 19:02:43,054 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:43,066 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:43,067 : send_data - Client @ Client.py (WARNING)] Could not send to port 3100 (the socket must be connected in order to send data).
[2016-11-21 19:02:46,775 : set_sending_datagram - Server @ Server.py (DEBUG)] Sending datagram set to : ['BOOL'] for server socket on port 1200
[2016-11-21 19:02:46,775 : set_sending_datagram - Server @ Server.py (DEBUG)] Sending datagram set to : ['BOOL'] for server socket on port 1210
[2016-11-21 19:02:46,775 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : ['SMALL_INT_SIGNED'] for server socket on port 1200
[2016-11-21 19:02:46,776 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : ['SMALL_INT_SIGNED'] for server socket on port 1210
[2016-11-21 19:02:50,829 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 19:02:50,830 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 19:02:50,830 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : ['SMALL_INT_SIGNED'] for client socket on port 1200
[2016-11-21 19:02:50,831 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : ['SMALL_INT_SIGNED'] for client socket on port 1210
[2016-11-21 19:02:50,831 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['BOOL'] for client socket on port 1200
[2016-11-21 19:02:50,832 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['BOOL'] for client socket on port 1210
[2016-11-21 19:02:50,832 : set_up_connection - Client @ Client.py (DEBUG)] Connection successful on port 1200.
[2016-11-21 19:02:50,833 : set_up_connection - Server @ Server.py (INFO)] Maximum amount of clients reached (1) on port 1200
[2016-11-21 19:02:50,833 : set_up_connection - Server @ Server.py (DEBUG)] 1 clients successfuly connected on port 1200
[2016-11-21 19:02:50,844 : set_up_connection - Client @ Client.py (DEBUG)] Connection successful on port 1210.
[2016-11-21 19:02:50,844 : set_up_connection - Server @ Server.py (INFO)] Maximum amount of clients reached (1) on port 1210
[2016-11-21 19:02:50,845 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : ['SMALL_INT_SIGNED'] for server socket on port 2200
[2016-11-21 19:02:50,845 : set_up_connection - Server @ Server.py (DEBUG)] 1 clients successfuly connected on port 1210
[2016-11-21 19:02:50,845 : set_sending_datagram - Server @ Server.py (DEBUG)] Sending datagram set to : ['SMALL_INT_SIGNED'] for server socket on port 2200
[2016-11-21 19:02:50,846 : listen_to_clients - Server @ Server.py (DEBUG)] Listening to clients on port 1200
[2016-11-21 19:02:50,847 : listen_to_clients - Server @ Server.py (DEBUG)] Listening to clients on port 1210
[2016-11-21 19:02:52,891 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 19:02:52,892 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : ['BOOL'] for client socket on port 2600
[2016-11-21 19:02:52,892 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['BOOL'] for client socket on port 2600
[2016-11-21 19:02:55,215 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 19:02:55,216 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : ['SMALL_INT_SIGNED'] for client socket on port 2200
[2016-11-21 19:02:55,217 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['SMALL_INT_SIGNED'] for client socket on port 2200
[2016-11-21 19:02:55,217 : set_up_connection - Client @ Client.py (DEBUG)] Connection successful on port 2200.
[2016-11-21 19:02:55,217 : set_up_connection - Server @ Server.py (INFO)] Maximum amount of clients reached (1) on port 2200
[2016-11-21 19:02:55,218 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : ['BOOL'] for server socket on port 3100
[2016-11-21 19:02:55,218 : set_up_connection - Server @ Server.py (DEBUG)] 1 clients successfuly connected on port 2200
[2016-11-21 19:02:55,219 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : ['SMALL_INT_SIGNED'] for server socket on port 2210
[2016-11-21 19:02:55,220 : set_sending_datagram - Server @ Server.py (DEBUG)] Sending datagram set to : ['SMALL_INT_SIGNED'] for server socket on port 2210
[2016-11-21 19:02:57,633 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 19:02:57,634 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : ['SMALL_INT_SIGNED'] for client socket on port 2210
[2016-11-21 19:02:57,634 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['SMALL_INT_SIGNED'] for client socket on port 2210
[2016-11-21 19:02:57,635 : set_up_connection - Client @ Client.py (DEBUG)] Connection successful on port 2210.
[2016-11-21 19:02:57,635 : set_up_connection - Server @ Server.py (INFO)] Maximum amount of clients reached (1) on port 2210
[2016-11-21 19:02:57,636 : set_up_connection - Server @ Server.py (DEBUG)] 1 clients successfuly connected on port 2210
[2016-11-21 19:02:57,637 : listen_to_clients - Server @ Server.py (DEBUG)] Listening to clients on port 2200
[2016-11-21 19:02:57,638 : listen_to_clients - Server @ Server.py (DEBUG)] Listening to clients on port 2210
[2016-11-21 19:02:57,902 : set_up_connection - Client @ Client.py (ERROR)] Connection refused on port 2600. Is the server running with available sockets ?
[2016-11-21 19:02:57,906 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 19:02:57,907 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : ['BOOL'] for client socket on port 3100
[2016-11-21 19:02:57,908 : set_up_connection - Client @ Client.py (DEBUG)] Connection successful on port 3100.
[2016-11-21 19:02:57,908 : set_up_connection - Server @ Server.py (INFO)] Maximum amount of clients reached (1) on port 3100
[2016-11-21 19:02:57,908 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:57,909 : set_up_connection - Server @ Server.py (DEBUG)] 1 clients successfuly connected on port 3100
[2016-11-21 19:02:57,910 : set_receiving_datagram - Server @ Server.py (DEBUG)] Receiving datagram set to : ['SMALL_INT_SIGNED'] for server socket on port 3110
[2016-11-21 19:02:57,911 : set_sending_datagram - Server @ Server.py (DEBUG)] Sending datagram set to : ['BOOL'] for server socket on port 3110
[2016-11-21 19:02:57,919 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:58,021 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:58,032 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:58,134 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:58,145 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:58,246 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:58,258 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:58,360 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:58,372 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:58,474 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:58,487 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:58,590 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:58,601 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:58,703 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:58,714 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:58,816 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:58,827 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:58,929 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:58,940 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:59,042 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:59,053 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:59,155 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:59,166 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:59,268 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:59,279 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:59,381 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:59,392 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:59,493 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:59,505 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:59,606 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:59,618 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:59,663 : __init__ - Client @ Client.py (DEBUG)] test
[2016-11-21 19:02:59,664 : set_sending_datagram - Client @ Client.py (DEBUG)] Sending datagram set to : ['SMALL_INT_SIGNED'] for client socket on port 3110
[2016-11-21 19:02:59,665 : set_receiving_datagram - Client @ Client.py (DEBUG)] Receiving datagram set to : ['BOOL'] for client socket on port 3110
[2016-11-21 19:02:59,665 : set_up_connection - Client @ Client.py (DEBUG)] Connection successful on port 3110.
[2016-11-21 19:02:59,666 : set_up_connection - Server @ Server.py (INFO)] Maximum amount of clients reached (1) on port 3110
[2016-11-21 19:02:59,666 : set_up_connection - Server @ Server.py (DEBUG)] 1 clients successfuly connected on port 3110
[2016-11-21 19:02:59,667 : listen_to_clients - Server @ Server.py (DEBUG)] Listening to clients on port 3110
[2016-11-21 19:02:59,668 : listen_to_clients - Server @ Server.py (DEBUG)] Listening to clients on port 3100
[2016-11-21 19:02:59,719 : send_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
[2016-11-21 19:02:59,731 : receive_data - Client @ Client.py (WARNING)] Could not send to port 2600 (the socket must be connected in order to send data).
