[2016-11-15 16:15:28,507 : receive_data - Client @ Client.py (ERROR)] An error occured : could not decode data "b'\x00'" from port 1600. Is the data compliant with the datagram?
[2016-11-15 16:15:31,010 : receive_data - Client @ Client.py (ERROR)] An error occured : could not decode data "b'\x01'" from port 1600. Is the data compliant with the datagram?
[2016-11-15 16:50:11,153 : send_data - Client @ Client.py (ERROR)] An error occured : could not send data to port 1400
